version: "3"
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=app

  redis:
    image: redis:6
    restart: always
    ports:
      - "6379:6379"
